import { Prisma } from "@prisma/client";

/**
 * Context payload provided to processors during preview generation.
 */
export interface PreviewContext {
    /**
     * Database ID of the File record.
     */
    fileId: string;

    /**
     * Name of the file with its extension.
     */
    fileName: string;

    /**
     * MIME type of the file.
     */
    mimeType: string;

    /**
     * Size of the original file in bytes.
     */
    size: number;

    /**
     * Path to the downloaded copy of the file on local disk.
     */
    localPath: string;
}

/**
 * The output result of a preview processor execution.
 */
export interface PreviewResult {
    /**
     * Optional thumbnail asset generated by the processor.
     */
    thumbnail?: {
        /**
         * Raw buffer content of the thumbnail file.
         */
        buffer: Buffer;

        /**
         * MIME type of the thumbnail (e.g. image/jpeg, image/webp).
         */
        mimeType: string;
    };

    /**
     * Optional transcoded or converted full preview asset (e.g. video WebM, document PDF).
     */
    preview?: {
        /**
         * Raw buffer content of the preview file.
         */
        buffer: Buffer;

        /**
         * MIME type of the preview file (e.g. application/pdf, video/webm).
         */
        mimeType: string;
    };

    /**
     * Flexible key-value metadata to store in the JSON database field.
     */
    metadata?: Record<string, any>;
}
